
#pragma once
#define VIAL_KEYBOARD_UID {0xD1, 0x47, 0xEF, 0x04, 0xFA, 0x4D, 0xD3, 0x8C}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 1}
#define VIAL_UNLOCK_COMBO_COLS { 0, 1} 

#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define DYNAMIC_KEYMAP_MACRO_COUNT 32